# Generated by Django 5.1.5 on 2025-10-13 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expensed_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='product',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('study', 'Study'), ('entertainment', 'Entertainment'), ('transport', 'Transport'), ('dining', 'Dining'), ('utilities', 'Utilities'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
